defaults: &defaults
  working_directory: /go/src/github.com/lukyth/try-go-kit/
  docker:
    - image: circleci/golang:1.9

version: 2
jobs:
  install-dep:
    <<: *defaults
    working_directory: /go
    steps:
      - run: go get -u github.com/golang/dep/cmd/dep
      - persist_to_workspace:
          root: .
          paths: go/
  install-dependencies-gateway:
    <<: *defaults
    steps:
      - checkout
      - run: cd gateway && dep ensure
      - persist_to_workspace:
          root: /go/src/github.com/lukyth/try-go-kit/gateway
          paths: vendor/
  install-dependencies-svc-add:
    <<: *defaults
    steps:
      - checkout
      - run: cd svc-add && dep ensure
      - persist_to_workspace:
          root: /go/src/github.com/lukyth/try-go-kit/svc-add
          paths: vendor/
  install-dependencies-svc-string:
    <<: *defaults
    steps:
      - checkout
      - run: cd svc-string && dep ensure
      - persist_to_workspace:
          root: /go/src/github.com/lukyth/try-go-kit/svc-string
          paths: vendor/
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - install-dep
      - install-dependencies-gateway:
          requires:
            - install-dep
      - install-dependencies-svc-add:
          requires:
            - install-dep
      - install-dependencies-svc-string:
          requires:
            - install-dep
