version: 2
jobs:
  install-dependencies-gateway:
    working_directory: /go/src/github.com/lukyth/try-go-kit/
    docker:
      - image: circleci/golang:1.9
    environment:
      TEST_RESULTS: /gateway/tmp/test-results
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/gateway
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd gateway && dep ensure
      - persist_to_workspace:
          root: gateway
          paths: vendor/
  install-dependencies-svc-add:
    working_directory: /go/src/github.com/lukyth/try-go-kit/
    docker:
      - image: circleci/golang:1.9
    environment:
      TEST_RESULTS: /gateway/tmp/test-results
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-add
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd gateway && dep ensure
      - persist_to_workspace:
          root: svc-add
          paths: vendor/
  install-dependencies-svc-string:
    working_directory: /go/src/github.com/lukyth/try-go-kit/
    docker:
      - image: circleci/golang:1.9
    environment:
      TEST_RESULTS: /gateway/tmp/test-results
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-string
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd gateway && dep ensure
      - persist_to_workspace:
          root: svc-string
          paths: vendor/
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - install-dependencies-gateway
      - install-dependencies-svc-add
      - install-dependencies-svc-string