version: 2
jobs:
  unit-test:
    working_directory: /go/src/github.com/lukyth/try-go-kit/
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: cd gateway && dep ensure -vendor-only
      - run: cd svc-add && dep ensure -vendor-only
      - run: cd svc-string && dep ensure -vendor-only
      - run: go test $(go list ./... | grep -v /vendor/)
  build-and-deploy:
    working_directory: /go/src/github.com/lukyth/try-go-kit/
    docker:
      - image: circleci/golang # will change soon
    environment:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce
      - restore_cache:
          key: gcloud-latest-{{ .Branch }}
      - run:
          name: Update gcloud SDK
          command: ${HOME}/google-cloud-sdk/bin/gcloud components update -q
      - save_cache:
          key: gcloud-latest-{{ .Branch }}-{{ checksum "VERSION_FILE" }}
          paths:
            - "${HOME}/google-cloud-sdk"
      - run:
          name: Auth gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            ${HOME}/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            ${HOME}/google-cloud-sdk/bin/gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${CLUSTER_ZONE} --project ${PROJECT_ID}
      - deploy:
          name: Deploy Master to GKE
          command: |
            ./deploy.sh gateway
            ./deploy.sh svc-add
            ./deploy.sh svc-string
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - unit-test
      - build-and-deploy:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - master
                - feature/circleci
