defaults: &defaults
  working_directory: /go/src/github.com/lukyth/try-go-kit/
  docker:
    - image: circleci/golang:1.9
    
version: 2
jobs:
  install-dependencies-gateway:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/gateway
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd gateway && dep ensure
      - persist_to_workspace:
          root: gateway
          paths: vendor/
  install-dependencies-svc-add:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-add
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd svc-add && dep ensure
      - persist_to_workspace:
          root: svc-add
          paths: vendor/
  install-dependencies-svc-string:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-string
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            cd svc-string && dep ensure
      - persist_to_workspace:
          root: svc-string
          paths: vendor/
  unit-test:
    <<: *defaults
    environment:
      TEST_RESULTS: /tmp/test-results
    steps: 
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/gateway
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-add
      - attach_workspace:
          at: /go/src/github.com/lukyth/try-go-kit/svc-string
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - run: make
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - install-dependencies-gateway
      - install-dependencies-svc-add
      - install-dependencies-svc-string
      - unit-test:
          requires:
            - install-dependencies-gateway
            - install-dependencies-svc-add
            - install-dependencies-svc-string
